sonar.projectKey=Notes-app
sonar.projectName=Notes app
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/.next/**, **/coverage/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.javascript.node.maxspace=4096